[package]
name = "cloudflare-ddns"
version = "0.4.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>"]
edition = "2018"
description = "A daemon to use Cloudflare as a DDNS provider"
repository = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
homepage = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
keywords = ["cloudflare", "ddns"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
documentation = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
readme = "README.md"

[dependencies]
reqwest= { version = "0.11.3", features = ["blocking", "json"] }
serde = { version = "1.0.126", features = ["derive"] }
anyhow = "1.0.40"
env_logger = "0.10.0"
log = "0.4.11"
tokio = { version = "1.6.0", features = ["macros"] }
serde_yaml = "0.9.17"
cloudflare = {git="https://github.com/cloudflare/cloudflare-rs", branch="master"}
clap = "4.1" # command line parse
pnet_datalink = "0.33.0"
ipnetwork = "0.20.0"

[patch.crates-io]
log = {git = "https://github.com/rust-lang/log", tag = "0.4.11"}
