[package]
name = "cloudflare-ddns"
version = "0.4.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>"]
edition = "2018"
description = "A daemon to use Cloudflare as a DDNS provider"
repository = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
homepage = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
keywords = ["cloudflare", "ddns"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
documentation = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
readme = "README.md"

[dependencies]
reqwest= { version = "0.11.3", features = ["blocking", "json"] }
serde = { version = "1.0.126", features = ["derive"] }
anyhow = "1.0.40"
env_logger = "0.9.0"
log = "0.4.11"
directories-next = "2.0.0"
tokio = { version = "1.6.0", features = ["time", "macros", "rt-multi-thread"] }
serde_yaml = "0.8.17"
cloudflare = {git="https://github.com/cloudflare/cloudflare-rs"}
clap = "3.0.0-beta.5" # command line parse
pnet = "0.29.0"
ipnetwork = "0.18"

[patch.crates-io]
log = {git = "https://github.com/rust-lang/log", tag = "0.4.11"}
