[package]
name = "cloudflare-ddns"
version = "0.4.0"
authors = ["Jan Christian Grünhage <jan.christian@gruenhage.xyz>"]
edition = "2018"
description = "A daemon to use Cloudflare as a DDNS provider"
repository = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
homepage = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
keywords = ["cloudflare", "ddns"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
documentation = "https://git.jcg.re/jcgruenhage/cloudflare-ddns-service"
readme = "README.md"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = { version = "1.0" }
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.25", features = ["macros"] }
serde_yaml = "0.9"
cloudflare = { git = "https://github.com/xgzeng/cloudflare-rs", branch = "master" }
clap = "4.1"
pnet_datalink = "0.33"
ipnetwork = "0.20"

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [
    ["debian/cloudflare-ddns.yaml", "etc/", "600"],
    ["target/release/cloudflare-ddns", "usr/bin/", "755"]
]
conf-files = ["/etc/cloudflare-ddns.yaml"]
systemd-units = { enable = false }