name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Packaging
        run: cargo deb
      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: target/debian/cloudflare-ddns_*.deb
      - uses: djnicholson/release-action@v2.11
        with:
          asset-name: 'cloudflare-ddns_0.4.0_amd64.deb'
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/debian/cloudflare-ddns_0.4.0_amd64.deb'
